DROP TABLE IF EXISTS PURCHASE_TRANSACTIONS;

CREATE TABLE PURCHASE_TRANSACTIONS (
ID VARCHAR(36) PRIMARY KEY,
PAYMENT_TYPE VARCHAR(20) NOT NULL,
AMOUNT DECIMAL(19,4),
CUSTOMER_ID VARCHAR(36),
CREATED_AT DATE NOT NULL
)

